services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lob-api-dev
    working_dir: /app
    volumes:
      - .:/app
      - lob_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: npm run start:api
    environment:
      NODE_ENV: development
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      REDIS_URL: redis://redis:6379

  matching-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lob-matching-worker-dev
    working_dir: /app
    volumes:
      - .:/app
      - lob_node_modules:/app/node_modules
    command: npm run start:worker
    environment:
      NODE_ENV: development
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      REDIS_URL: redis://redis:6379

  matching-standby:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lob-matching-standby
    working_dir: /app
    volumes:
      - .:/app
      - lob_node_modules:/app/node_modules
    command: npm run start:standby
    environment:
      NODE_ENV: development
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - rabbitmq

  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lob-websocket-dev
    working_dir: /app
    volumes:
      - .:/app
      - lob_node_modules:/app/node_modules
    ports:
      - "3001:3001"
    command: npm run start:websocket
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379

  rabbitmq:
    image: rabbitmq:3-management
    container_name: lob-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    container_name: lob-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  lob_node_modules:
  rabbitmq_data:
  redis_data:
