export const OrderCommandType = Object.freeze({
  PLACE_LIMIT_ORDER: "PLACE_LIMIT_ORDER",
  PLACE_MARKET_ORDER: "PLACE_MARKET_ORDER",
  PLACE_STOP_MARKET_ORDER: "PLACE_STOP_MARKET_ORDER",
  PLACE_STOP_LIMIT_ORDER: "PLACE_STOP_LIMIT_ORDER",
  PLACE_TRAILING_STOP_MARKET_ORDER: "PLACE_TRAILING_STOP_MARKET_ORDER",
  CANCEL_ORDER: "CANCEL_ORDER",
});
